# Site settings
title: RXDart
description: Jekyll Theme based on Semantic UI
analytics: UA-XXXXXXXX-X
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Social Networks
social:
  - title: facebook
    url: "https://www.facebook.com/XXX"
  - title: twitter
    url: "https://twitter.com/xljroXX"
  - title: instagram
    url: "http://instagram.com/XXX"
  - title: google-plus
    url: "https://plus.google.com/+XXX"
  - title: linkedin
    url: "https://cn.linkedin.com/in/XXX"
  - title: github
    url: "https://github.com/XXX"
  - title: picture-o
    url: "https://500px.com/XXX"

# Contacts
email: XXX@gmail.com

